-- Auto-generated by scripts/import-august-catalog.ts — do not hand-edit.
-- Source: data/BlackBox_August_Catalogue.xlsx
-- Idempotent upserts into products + product_variants (Audio + Laptops).
BEGIN;

-- Widen products.category for Headphones / Speakers / Laptops (and full taxonomy)
ALTER TABLE public.products DROP CONSTRAINT IF EXISTS products_category_check;
ALTER TABLE public.products
  ADD CONSTRAINT products_category_check
  CHECK (
    category IS NULL
    OR category IN (
      'iPhone', 'Android phones', 'iPad', 'MacBooks', 'Laptops',
      'Smart watches', 'Gaming', 'Headphones', 'Speakers', 'Accessories',
      'Laptop', 'Audio', 'Tablet', 'Trades'
    )
  );

-- Widen products.subcategory for August series slugs
ALTER TABLE public.products DROP CONSTRAINT IF EXISTS products_subcategory_check;
ALTER TABLE public.products
  ADD CONSTRAINT products_subcategory_check
  CHECK (
    subcategory IS NULL
    OR subcategory IN (
      'new', 'used', 'preowned', 'refurbished',
      'iWatches', 'Others',
      'PlayStation', 'Xbox', 'Steam', 'Nintendo',
      'AirPods', 'JBL', 'Sony', 'EarPods', 'Beats',
      'HomePod', 'HarmanKardon',
      'PhoneCases', 'ScreenProtectors', 'Chargers',
      'HP', 'Dell',
      -- Audio series
      'Tune', 'Solo', 'Flip', 'Charge', 'Boombox', 'Go', 'Onyx', 'Pill',
      -- Laptop series
      'Omen', 'Envy', 'Victus', 'Alienware',
      -- iPad / MacBook series
      'pro', 'air', 'mini', 'standard', 'other',
      -- iPhone series
      'iphone-17', 'iphone-16', 'iphone-15', 'iphone-14',
      'iphone-13', 'iphone-12', 'iphone-11', 'iphone-x',
      'iphone-se', 'iphone-older'
    )
  );

-- Product: AirPods Max 2nd Gen (2026) (Headphones)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'AirPods Max 2nd Gen (2026)', 'apple-airpods-max-2nd-gen-2026-new', 'Apple', 'Headphones',
  'AirPods', 'new', 'active', 5999, 'GHS', 0,
  'Apple AirPods Max 2nd Gen (2026) — brand new',
  '{"catalog":"audio","audio_type":"headphones","series":"AirPods"}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'APPLE-AIRPODSMAX2NDGEN2026-NEW', NULL, NULL, NULL, NULL, NULL,
  5999, 0, true, NULL, '{"status":"active","catalog":"audio","series":"AirPods","model_slug":"apple-airpods-max-2nd-gen-2026-new","source_sku":"APPLE-AIRPODSMAX2NDGEN2026"}'::jsonb
FROM public.products p
WHERE p.slug = 'apple-airpods-max-2nd-gen-2026-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: AirPods Pro 3 (Headphones)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'AirPods Pro 3', 'apple-airpods-pro-3-new', 'Apple', 'Headphones',
  'AirPods', 'new', 'active', 2899, 'GHS', 0,
  'Apple AirPods Pro 3 — brand new',
  '{"catalog":"audio","audio_type":"headphones","series":"AirPods"}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'APPLE-AIRPODSPRO3-NEW', NULL, NULL, NULL, NULL, NULL,
  2899, 0, true, NULL, '{"status":"active","catalog":"audio","series":"AirPods","model_slug":"apple-airpods-pro-3-new","source_sku":"APPLE-AIRPODSPRO3"}'::jsonb
FROM public.products p
WHERE p.slug = 'apple-airpods-pro-3-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: AirPods 4 (ANC) (Headphones)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'AirPods 4 (ANC)', 'apple-airpods-4-anc-new', 'Apple', 'Headphones',
  'AirPods', 'new', 'active', 2499, 'GHS', 0,
  'Apple AirPods 4 (ANC) — brand new',
  '{"catalog":"audio","audio_type":"headphones","series":"AirPods"}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'APPLE-AIRPODS4ANC-NEW', NULL, NULL, NULL, NULL, NULL,
  2499, 0, true, NULL, '{"status":"active","catalog":"audio","series":"AirPods","model_slug":"apple-airpods-4-anc-new","source_sku":"APPLE-AIRPODS4ANC"}'::jsonb
FROM public.products p
WHERE p.slug = 'apple-airpods-4-anc-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: AirPods 4 (NNC) (Headphones)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'AirPods 4 (NNC)', 'apple-airpods-4-nnc-new', 'Apple', 'Headphones',
  'AirPods', 'new', 'active', 1799, 'GHS', 0,
  'Apple AirPods 4 (NNC) — brand new',
  '{"catalog":"audio","audio_type":"headphones","series":"AirPods"}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'APPLE-AIRPODS4NNC-NEW', NULL, NULL, NULL, NULL, NULL,
  1799, 0, true, NULL, '{"status":"active","catalog":"audio","series":"AirPods","model_slug":"apple-airpods-4-nnc-new","source_sku":"APPLE-AIRPODS4NNC"}'::jsonb
FROM public.products p
WHERE p.slug = 'apple-airpods-4-nnc-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Tune 520BT (Headphones)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Tune 520BT', 'jbl-tune-520bt-new', 'JBL', 'Headphones',
  'Tune', 'new', 'active', 699, 'GHS', 0,
  'JBL Tune 520BT — brand new',
  '{"catalog":"audio","audio_type":"headphones","series":"Tune"}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'JBL-TUNE520BT-NEW', NULL, NULL, NULL, NULL, NULL,
  699, 0, true, NULL, '{"status":"active","catalog":"audio","series":"Tune","model_slug":"jbl-tune-520bt-new","source_sku":"JBL-TUNE520BT"}'::jsonb
FROM public.products p
WHERE p.slug = 'jbl-tune-520bt-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Tune 730BT (Headphones)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Tune 730BT', 'jbl-tune-730bt-new', 'JBL', 'Headphones',
  'Tune', 'new', 'active', 9999, 'GHS', 0,
  'JBL Tune 730BT — brand new',
  '{"catalog":"audio","audio_type":"headphones","series":"Tune"}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'JBL-TUNE730BT-NEW', NULL, NULL, NULL, NULL, NULL,
  9999, 0, true, NULL, '{"status":"active","catalog":"audio","series":"Tune","model_slug":"jbl-tune-730bt-new","source_sku":"JBL-TUNE730BT"}'::jsonb
FROM public.products p
WHERE p.slug = 'jbl-tune-730bt-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Solo Pro (Headphones)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Solo Pro', 'beats-solo-pro-new', 'Beats', 'Headphones',
  'Solo', 'new', 'active', 1699, 'GHS', 0,
  'Beats Solo Pro — brand new',
  '{"catalog":"audio","audio_type":"headphones","series":"Solo"}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'BEATS-SOLOPRO-NEW', NULL, NULL, NULL, NULL, NULL,
  1699, 0, true, NULL, '{"status":"active","catalog":"audio","series":"Solo","model_slug":"beats-solo-pro-new","source_sku":"BEATS-SOLOPRO"}'::jsonb
FROM public.products p
WHERE p.slug = 'beats-solo-pro-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Onyx Studio 9 (Speakers)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Onyx Studio 9', 'harman-kardon-onyx-studio-9-new', 'Harman Kardon', 'Speakers',
  'Onyx', 'new', 'active', 2899, 'GHS', 0,
  'Harman Kardon Onyx Studio 9 — brand new',
  '{"catalog":"audio","audio_type":"speakers","series":"Onyx"}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'HARMANKARDON-ONYXSTUDIO9-NEW', NULL, NULL, NULL, NULL, NULL,
  2899, 0, true, NULL, '{"status":"active","catalog":"audio","series":"Onyx","model_slug":"harman-kardon-onyx-studio-9-new","source_sku":"HARMANKARDON-ONYXSTUDIO9"}'::jsonb
FROM public.products p
WHERE p.slug = 'harman-kardon-onyx-studio-9-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Flip 6 (Speakers)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Flip 6', 'jbl-flip-6-new', 'JBL', 'Speakers',
  'Flip', 'new', 'active', 1499, 'GHS', 0,
  'JBL Flip 6 — brand new',
  '{"catalog":"audio","audio_type":"speakers","series":"Flip"}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'JBL-FLIP6-NEW', NULL, NULL, NULL, NULL, NULL,
  1499, 0, true, NULL, '{"status":"active","catalog":"audio","series":"Flip","model_slug":"jbl-flip-6-new","source_sku":"JBL-FLIP6"}'::jsonb
FROM public.products p
WHERE p.slug = 'jbl-flip-6-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Flip 7 (Speakers)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Flip 7', 'jbl-flip-7-new', 'JBL', 'Speakers',
  'Flip', 'new', 'active', 1699, 'GHS', 0,
  'JBL Flip 7 — brand new',
  '{"catalog":"audio","audio_type":"speakers","series":"Flip"}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'JBL-FLIP7-NEW', NULL, NULL, NULL, NULL, NULL,
  1699, 0, true, NULL, '{"status":"active","catalog":"audio","series":"Flip","model_slug":"jbl-flip-7-new","source_sku":"JBL-FLIP7"}'::jsonb
FROM public.products p
WHERE p.slug = 'jbl-flip-7-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Charge 6 (Speakers)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Charge 6', 'jbl-charge-6-new', 'JBL', 'Speakers',
  'Charge', 'new', 'active', 2249, 'GHS', 0,
  'JBL Charge 6 — brand new',
  '{"catalog":"audio","audio_type":"speakers","series":"Charge"}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'JBL-CHARGE6-NEW', NULL, NULL, NULL, NULL, NULL,
  2249, 0, true, NULL, '{"status":"active","catalog":"audio","series":"Charge","model_slug":"jbl-charge-6-new","source_sku":"JBL-CHARGE6"}'::jsonb
FROM public.products p
WHERE p.slug = 'jbl-charge-6-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Boombox 3 (Speakers)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Boombox 3', 'jbl-boombox-3-new', 'JBL', 'Speakers',
  'Boombox', 'new', 'active', 5999, 'GHS', 0,
  'JBL Boombox 3 — brand new',
  '{"catalog":"audio","audio_type":"speakers","series":"Boombox"}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'JBL-BOOMBOX3-NEW', NULL, NULL, NULL, NULL, NULL,
  5999, 0, true, NULL, '{"status":"active","catalog":"audio","series":"Boombox","model_slug":"jbl-boombox-3-new","source_sku":"JBL-BOOMBOX3"}'::jsonb
FROM public.products p
WHERE p.slug = 'jbl-boombox-3-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Go 4 (Speakers)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Go 4', 'jbl-go-4-new', 'JBL', 'Speakers',
  'Go', 'new', 'active', 649, 'GHS', 0,
  'JBL Go 4 — brand new',
  '{"catalog":"audio","audio_type":"speakers","series":"Go"}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'JBL-GO4-NEW', NULL, NULL, NULL, NULL, NULL,
  649, 0, true, NULL, '{"status":"active","catalog":"audio","series":"Go","model_slug":"jbl-go-4-new","source_sku":"JBL-GO4"}'::jsonb
FROM public.products p
WHERE p.slug = 'jbl-go-4-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Pill 3rd Gen (2024) (Speakers)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Pill 3rd Gen (2024)', 'beats-pill-3rd-gen-2024-new', 'Beats', 'Speakers',
  'Pill', 'new', 'active', 1699, 'GHS', 0,
  'Beats Pill 3rd Gen (2024) — brand new',
  '{"catalog":"audio","audio_type":"speakers","series":"Pill"}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'BEATS-PILL3RDGEN2024-NEW', NULL, NULL, NULL, NULL, NULL,
  1699, 0, true, NULL, '{"status":"active","catalog":"audio","series":"Pill","model_slug":"beats-pill-3rd-gen-2024-new","source_sku":"BEATS-PILL3RDGEN2024"}'::jsonb
FROM public.products p
WHERE p.slug = 'beats-pill-3rd-gen-2024-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Omen Transcend 14 (Laptops)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Omen Transcend 14', 'hp-omen-transcend-14-new-1tb', 'HP', 'Laptops',
  'Omen', 'new', 'active', 13499, 'GHS', 0,
  'HP Omen Transcend 14 · 1TB SSD — brand new',
  '{"catalog":"laptop","series":"Omen","processor":null,"generation":null,"storage_label":"1TB SSD","memory":"16GB RAM","graphics":null,"display":null,"battery":null,"os":null,"extras":"RGB KEYBOARD"}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY['1TB']::TEXT[], ARRAY['16GB']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'HP-OMENTRANSCEND14-1TBSSD-NEW', NULL, '1TB', '16GB', NULL, NULL,
  13499, 0, true, NULL, '{"status":"active","catalog":"laptop","series":"Omen","model_slug":"hp-omen-transcend-14-new-1tb","source_sku":"HP-OMENTRANSCEND14-1TBSSD"}'::jsonb
FROM public.products p
WHERE p.slug = 'hp-omen-transcend-14-new-1tb'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Envy 15 (Laptops)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Envy 15', 'hp-envy-15-new-512gb', 'HP', 'Laptops',
  'Envy', 'new', 'active', 9499, 'GHS', 0,
  'HP Envy 15 · 512GB SSD — brand new',
  '{"catalog":"laptop","series":"Envy","processor":"AMD RYZEN 5 7530U","generation":null,"storage_label":"512GB SSD","memory":"16GB RAM DDR5","graphics":null,"display":"15\" FHD TOUCH DISPLAY","battery":null,"os":"WINDOWS 11","extras":"TOUCH SCREEN, FACIAL RECOGNITION, BACKLIGHT KEYBOARD"}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY['512GB']::TEXT[], ARRAY['16GB']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'HP-ENVY15-512GBSSD-NEW', NULL, '512GB', '16GB', NULL, NULL,
  9499, 0, true, NULL, '{"status":"active","catalog":"laptop","series":"Envy","model_slug":"hp-envy-15-new-512gb","source_sku":"HP-ENVY15-512GBSSD"}'::jsonb
FROM public.products p
WHERE p.slug = 'hp-envy-15-new-512gb'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Victus 16 (Laptops)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Victus 16', 'hp-victus-16-new-1tb', 'HP', 'Laptops',
  'Victus', 'new', 'active', 10499, 'GHS', 0,
  'HP Victus 16 · 1TB SSD — brand new',
  '{"catalog":"laptop","series":"Victus","processor":"AMD RYZEN 5 8645HS","generation":"14TH GENERATION","storage_label":"1TB SSD","memory":"16GB RAM","graphics":"NVIDIA GeFORCE RTX 4050 6GB DEDICATED","display":"15.6\" FHD IPS LED DISPLAY (1920x1080)","battery":null,"os":"WINDOWS 11","extras":null}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY['1TB']::TEXT[], ARRAY['16GB']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'HP-VICTUS16-1TBSSD-NEW', NULL, '1TB', '16GB', NULL, NULL,
  10499, 0, true, NULL, '{"status":"active","catalog":"laptop","series":"Victus","model_slug":"hp-victus-16-new-1tb","source_sku":"HP-VICTUS16-1TBSSD"}'::jsonb
FROM public.products p
WHERE p.slug = 'hp-victus-16-new-1tb'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Alienware 16 Aurora (Laptops)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Alienware 16 Aurora', 'dell-alienware-16-aurora-new-1tb', 'Dell', 'Laptops',
  'Alienware', 'new', 'active', 24999, 'GHS', 0,
  'Dell Alienware 16 Aurora · 1TB SSD — brand new',
  '{"catalog":"laptop","series":"Alienware","processor":"INTEL CORE 7 240H (36MB CACHE, 16 CPUs, 2.5 TO 5.2 GHz)","generation":null,"storage_label":"1TB M.2 PCIe NVMe SSD","memory":"32GB (2x16GB), DDR5 RAM","graphics":"NVIDIA GeFORCE RTX 5060, 8GB GDDR7","display":"16\" WQXGA 240Hz DCI-P3 COMFORT VIEW PLUS, G-SYNC","battery":null,"os":"WINDOWS 11 HOME","extras":"RGB KEYBOARD"}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY['1TB']::TEXT[], ARRAY['32GB']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'DELL-ALIENWARE16AURORA-1TBSSD-NEW', NULL, '1TB', '32GB', NULL, NULL,
  24999, 0, true, NULL, '{"status":"active","catalog":"laptop","series":"Alienware","model_slug":"dell-alienware-16-aurora-new-1tb","source_sku":"DELL-ALIENWARE16AURORA-1TBSSD"}'::jsonb
FROM public.products p
WHERE p.slug = 'dell-alienware-16-aurora-new-1tb'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Refresh base price / stock from variants for seeded catalogue rows
UPDATE public.products p SET
  price = COALESCE((SELECT MIN(pv.price) FROM public.product_variants pv WHERE pv.product_id = p.id AND pv.is_active AND pv.price > 0), p.price),
  stock = COALESCE((SELECT SUM(pv.stock) FROM public.product_variants pv WHERE pv.product_id = p.id), p.stock),
  updated_at = NOW()
WHERE p.specifications->>'catalog' IN ('audio', 'laptop')
  AND p.condition = 'new';

COMMIT;