-- Auto-generated by scripts/import-consoles.ts — do not hand-edit.
-- Source: data/BlackBox_Consoles.xlsx + CONSOLES AND CONTROLLERS PRICING.docx
-- Idempotent upserts into products + product_variants.
BEGIN;

ALTER TABLE public.products DROP CONSTRAINT IF EXISTS products_category_check;
ALTER TABLE public.products
  ADD CONSTRAINT products_category_check
  CHECK (
    category IS NULL
    OR category IN (
      'iPhone', 'Android phones', 'iPad', 'MacBooks', 'Laptops',
      'Smart watches', 'Gaming', 'Headphones', 'Speakers', 'Accessories',
      'Consoles', 'Controllers',
      'Laptop', 'Audio', 'Tablet', 'Trades'
    )
  );

ALTER TABLE public.products DROP CONSTRAINT IF EXISTS products_subcategory_check;
ALTER TABLE public.products
  ADD CONSTRAINT products_subcategory_check
  CHECK (
    subcategory IS NULL
    OR subcategory IN (
      'new', 'used', 'preowned', 'refurbished',
      'iWatches', 'Others',
      'PlayStation', 'Xbox', 'Steam', 'Nintendo',
      'AirPods', 'JBL', 'Sony', 'EarPods', 'Beats',
      'HomePod', 'HarmanKardon',
      'PhoneCases', 'ScreenProtectors', 'Chargers',
      'HP', 'Dell',
      'Tune', 'Solo', 'Flip', 'Charge', 'Boombox', 'Go', 'Onyx', 'Pill',
      'Omen', 'Envy', 'Victus', 'Alienware',
      'pro', 'air', 'mini', 'standard', 'other',
      'iphone-17', 'iphone-16', 'iphone-15', 'iphone-14',
      'iphone-13', 'iphone-12', 'iphone-11', 'iphone-x',
      'iphone-se', 'iphone-older',
      -- Console / controller series
      'PlayStation 5', 'PlayStation Portal', 'Xbox Series',
      'Switch', 'Steam Deck', 'DualSense'
    )
  );

-- Product: PlayStation 5 Slim (Consoles)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'PlayStation 5 Slim', 'sony-playstation-5-slim-new', 'Sony', 'Consoles',
  'PlayStation 5', 'new', 'active', 6899, 'GHS', 0,
  'Sony PlayStation 5 Slim · 1TB — Brand new',
  '{"catalog":"console","model_slug":"playstation-5-slim","series":"PlayStation 5","storage_label":"1TB","has_edition_axis":true}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY['1TB']::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, edition, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'SONY-PLAYSTATION5SLIM-DIGITAL-1TB', NULL, '1TB', NULL, NULL, NULL, 'Digital',
  6899, 0, true, NULL, '{"status":"active","catalog":"console","series":"PlayStation 5","model_slug":"playstation-5-slim","source_sku":"SONY-PLAYSTATION5SLIM-DIGITAL-1TB","edition":"Digital","storage_label":"1TB"}'::jsonb
FROM public.products p
WHERE p.slug = 'sony-playstation-5-slim-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  edition = EXCLUDED.edition,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, edition, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'SONY-PLAYSTATION5SLIM-STANDARD-1TB', NULL, '1TB', NULL, NULL, NULL, 'Standard',
  7599, 0, true, NULL, '{"status":"active","catalog":"console","series":"PlayStation 5","model_slug":"playstation-5-slim","source_sku":"SONY-PLAYSTATION5SLIM-STANDARD-1TB","edition":"Standard","storage_label":"1TB"}'::jsonb
FROM public.products p
WHERE p.slug = 'sony-playstation-5-slim-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  edition = EXCLUDED.edition,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: PlayStation 5 Pro (Consoles)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'PlayStation 5 Pro', 'sony-playstation-5-pro-new', 'Sony', 'Consoles',
  'PlayStation 5', 'new', 'active', 9999, 'GHS', 0,
  'Sony PlayStation 5 Pro · 2TB — Brand new',
  '{"catalog":"console","model_slug":"playstation-5-pro","series":"PlayStation 5","storage_label":"2TB","has_edition_axis":false}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY['2TB']::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, edition, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'SONY-PLAYSTATION5PRO-2TB', NULL, '2TB', NULL, NULL, NULL, NULL,
  9999, 0, true, NULL, '{"status":"active","catalog":"console","series":"PlayStation 5","model_slug":"playstation-5-pro","source_sku":"SONY-PLAYSTATION5PRO-2TB","edition":null,"storage_label":"2TB"}'::jsonb
FROM public.products p
WHERE p.slug = 'sony-playstation-5-pro-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  edition = EXCLUDED.edition,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: PlayStation Portal (Consoles)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'PlayStation Portal', 'sony-playstation-portal-new', 'Sony', 'Consoles',
  'PlayStation Portal', 'new', 'active', 2899, 'GHS', 0,
  'Sony PlayStation Portal — Brand new',
  '{"catalog":"console","model_slug":"playstation-portal","series":"PlayStation Portal","storage_label":null,"has_edition_axis":false}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, edition, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'SONY-PLAYSTATIONPORTAL', NULL, NULL, NULL, NULL, NULL, NULL,
  2899, 0, true, NULL, '{"status":"active","catalog":"console","series":"PlayStation Portal","model_slug":"playstation-portal","source_sku":"SONY-PLAYSTATIONPORTAL","edition":null,"storage_label":null}'::jsonb
FROM public.products p
WHERE p.slug = 'sony-playstation-portal-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  edition = EXCLUDED.edition,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Xbox Series S (Consoles)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Xbox Series S', 'microsoft-xbox-series-s-new', 'Microsoft', 'Consoles',
  'Xbox Series', 'new', 'active', 4999, 'GHS', 0,
  'Microsoft Xbox Series S · 1TB — Brand new',
  '{"catalog":"console","model_slug":"xbox-series-s","series":"Xbox Series","storage_label":"1TB","has_edition_axis":false}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY['1TB']::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, edition, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'MICROSOFT-XBOXSERIESS-DIGITAL-1TB', NULL, '1TB', NULL, NULL, NULL, 'Digital',
  4999, 0, true, NULL, '{"status":"active","catalog":"console","series":"Xbox Series","model_slug":"xbox-series-s","source_sku":"MICROSOFT-XBOXSERIESS-DIGITAL-1TB","edition":"Digital","storage_label":"1TB"}'::jsonb
FROM public.products p
WHERE p.slug = 'microsoft-xbox-series-s-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  edition = EXCLUDED.edition,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Xbox Series X (Consoles)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Xbox Series X', 'microsoft-xbox-series-x-new', 'Microsoft', 'Consoles',
  'Xbox Series', 'new', 'active', 8499, 'GHS', 0,
  'Microsoft Xbox Series X · 1TB — Brand new',
  '{"catalog":"console","model_slug":"xbox-series-x","series":"Xbox Series","storage_label":"1TB","has_edition_axis":false}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY['1TB']::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, edition, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'MICROSOFT-XBOXSERIESX-DISC-1TB', NULL, '1TB', NULL, NULL, NULL, 'Disc',
  8499, 0, true, NULL, '{"status":"active","catalog":"console","series":"Xbox Series","model_slug":"xbox-series-x","source_sku":"MICROSOFT-XBOXSERIESX-DISC-1TB","edition":"Disc","storage_label":"1TB"}'::jsonb
FROM public.products p
WHERE p.slug = 'microsoft-xbox-series-x-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  edition = EXCLUDED.edition,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Switch 2 (Consoles)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Switch 2', 'nintendo-switch-2-new', 'Nintendo', 'Consoles',
  'Switch', 'new', 'active', 6499, 'GHS', 0,
  'Nintendo Switch 2 · 256GB — Brand new',
  '{"catalog":"console","model_slug":"switch-2","series":"Switch","storage_label":"256GB","has_edition_axis":false}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY['256GB']::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, edition, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'NINTENDO-SWITCH2-256GB', NULL, '256GB', NULL, NULL, NULL, NULL,
  6499, 0, true, NULL, '{"status":"active","catalog":"console","series":"Switch","model_slug":"switch-2","source_sku":"NINTENDO-SWITCH2-256GB","edition":null,"storage_label":"256GB"}'::jsonb
FROM public.products p
WHERE p.slug = 'nintendo-switch-2-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  edition = EXCLUDED.edition,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Switch OLED (Consoles)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Switch OLED', 'nintendo-switch-oled-new', 'Nintendo', 'Consoles',
  'Switch', 'new', 'active', 4499, 'GHS', 0,
  'Nintendo Switch OLED · 64GB — Brand new',
  '{"catalog":"console","model_slug":"switch-oled","series":"Switch","storage_label":"64GB","has_edition_axis":false}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY['64GB']::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, edition, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'NINTENDO-SWITCHOLED-64GB', NULL, '64GB', NULL, NULL, NULL, NULL,
  4499, 0, true, NULL, '{"status":"active","catalog":"console","series":"Switch","model_slug":"switch-oled","source_sku":"NINTENDO-SWITCHOLED-64GB","edition":null,"storage_label":"64GB"}'::jsonb
FROM public.products p
WHERE p.slug = 'nintendo-switch-oled-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  edition = EXCLUDED.edition,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Steam Deck OLED (Consoles)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Steam Deck OLED', 'valve-steam-deck-oled-new', 'Valve', 'Consoles',
  'Steam Deck', 'new', 'active', 9499, 'GHS', 0,
  'Valve Steam Deck OLED · 512GB — Brand new',
  '{"catalog":"console","model_slug":"steam-deck-oled","series":"Steam Deck","storage_label":"512GB","has_edition_axis":false}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY['512GB']::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, edition, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'VALVE-STEAMDECKOLED-512GB', NULL, '512GB', NULL, NULL, NULL, NULL,
  9499, 0, true, NULL, '{"status":"active","catalog":"console","series":"Steam Deck","model_slug":"steam-deck-oled","source_sku":"VALVE-STEAMDECKOLED-512GB","edition":null,"storage_label":"512GB"}'::jsonb
FROM public.products p
WHERE p.slug = 'valve-steam-deck-oled-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  edition = EXCLUDED.edition,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: DualSense Wireless Controller (Controllers)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'DualSense Wireless Controller', 'sony-dualsense-wireless-controller-new', 'Sony', 'Controllers',
  'DualSense', 'new', 'active', 899, 'GHS', 0,
  'Sony DualSense Wireless Controller — Brand new',
  '{"catalog":"controller","model_slug":"dualsense-wireless-controller","series":"DualSense","storage_label":null,"has_edition_axis":false}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, edition, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'SONY-DUALSENSEWIRELESSCONTROLLER', NULL, NULL, NULL, NULL, NULL, NULL,
  899, 0, true, NULL, '{"status":"active","catalog":"controller","series":"DualSense","model_slug":"dualsense-wireless-controller","source_sku":"SONY-DUALSENSEWIRELESSCONTROLLER","edition":null,"storage_label":null}'::jsonb
FROM public.products p
WHERE p.slug = 'sony-dualsense-wireless-controller-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  edition = EXCLUDED.edition,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: DualSense Edge Wireless Controller (Controllers)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'DualSense Edge Wireless Controller', 'sony-dualsense-edge-wireless-controller-new', 'Sony', 'Controllers',
  'DualSense', 'new', 'active', 2599, 'GHS', 0,
  'Sony DualSense Edge Wireless Controller — Brand new',
  '{"catalog":"controller","model_slug":"dualsense-edge-wireless-controller","series":"DualSense","storage_label":null,"has_edition_axis":false}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, edition, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'SONY-DUALSENSEEDGEWIRELESSCONTROLLER', NULL, NULL, NULL, NULL, NULL, NULL,
  2599, 0, true, NULL, '{"status":"active","catalog":"controller","series":"DualSense","model_slug":"dualsense-edge-wireless-controller","source_sku":"SONY-DUALSENSEEDGEWIRELESSCONTROLLER","edition":null,"storage_label":null}'::jsonb
FROM public.products p
WHERE p.slug = 'sony-dualsense-edge-wireless-controller-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  edition = EXCLUDED.edition,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

-- Product: Xbox Controller (Controllers)
INSERT INTO public.products (
  name, slug, brand, category, subcategory, condition, status, price, currency, stock,
  description, specifications, is_new, featured, colors, storage, ram
) VALUES (
  'Xbox Controller', 'microsoft-xbox-controller-new', 'Microsoft', 'Controllers',
  'Xbox', 'new', 'active', 999, 'GHS', 0,
  'Microsoft Xbox Controller — Brand new',
  '{"catalog":"controller","model_slug":"xbox-controller","series":"Xbox","storage_label":null,"has_edition_axis":false}'::jsonb, true, false,
  ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory,
  condition = EXCLUDED.condition,
  status = EXCLUDED.status,
  price = EXCLUDED.price,
  description = EXCLUDED.description,
  specifications = EXCLUDED.specifications,
  is_new = EXCLUDED.is_new,
  colors = EXCLUDED.colors,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  updated_at = NOW();

INSERT INTO public.product_variants (
  product_id, sku, color, storage, ram, sim_type, display_size, edition, price, stock, is_active, image_url, attributes
) SELECT
  p.id, 'MICROSOFT-XBOXCONTROLLER', NULL, NULL, NULL, NULL, NULL, NULL,
  999, 0, true, NULL, '{"status":"active","catalog":"controller","series":"Xbox","model_slug":"xbox-controller","source_sku":"MICROSOFT-XBOXCONTROLLER","edition":null,"storage_label":null}'::jsonb
FROM public.products p
WHERE p.slug = 'microsoft-xbox-controller-new'
ON CONFLICT (sku) WHERE sku IS NOT NULL DO UPDATE SET
  color = EXCLUDED.color,
  storage = EXCLUDED.storage,
  ram = EXCLUDED.ram,
  sim_type = EXCLUDED.sim_type,
  display_size = EXCLUDED.display_size,
  edition = EXCLUDED.edition,
  price = EXCLUDED.price,
  is_active = EXCLUDED.is_active,
  image_url = COALESCE(EXCLUDED.image_url, product_variants.image_url),
  attributes = EXCLUDED.attributes,
  updated_at = NOW();

UPDATE public.products p SET
  price = COALESCE((SELECT MIN(pv.price) FROM public.product_variants pv WHERE pv.product_id = p.id AND pv.is_active AND pv.price > 0), p.price),
  stock = COALESCE((SELECT SUM(pv.stock) FROM public.product_variants pv WHERE pv.product_id = p.id), p.stock),
  updated_at = NOW()
WHERE p.specifications->>'catalog' IN ('console', 'controller')
  AND p.condition = 'new';

COMMIT;